# Generated by Django 4.1.7 on 2023-04-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tex',
            new_name='tax',
        ),
    ]
